-- phpMyAdmin SQL Dump
-- version 5.0.4
-- https://www.phpmyadmin.net/
--
-- Anamakine: 127.0.0.1
-- Üretim Zamanı: 14 Haz 2021, 13:22:53
-- Sunucu sürümü: 10.4.17-MariaDB
-- PHP Sürümü: 8.0.0

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Veritabanı: `koskitap_db`
--

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `books`
--

CREATE TABLE `books` (
  `bookId` int(11) NOT NULL,
  `bookName` varchar(40) NOT NULL,
  `bookAuthor` varchar(40) NOT NULL,
  `bookPublisher` varchar(50) NOT NULL,
  `bookType` varchar(50) NOT NULL DEFAULT 'Roman',
  `bookPage` bigint(20) NOT NULL,
  `bookPrice` int(11) NOT NULL,
  `bookDescription` text NOT NULL,
  `bookImage` varchar(25) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Tablo döküm verisi `books`
--

INSERT INTO `books` (`bookId`, `bookName`, `bookAuthor`, `bookPublisher`, `bookType`, `bookPage`, `bookPrice`, `bookDescription`, `bookImage`) VALUES
(1, 'Suç ve Ceza', 'Fyodor Mihayloviç Dostoyevski', 'İş Bankası Kültür Yayınları', 'Rus Edebiyatı', 687, 14, 'Fyodor Mihayloviç Dostoyevski (1821-1881): İlk romanı İnsancıklar 1846\'da yayımlandı. Ünlü eleştirmen V. Belinski bu eser üzerine Dostoyevski’den geleceğin büyük yazarı olarak söz etti. Ancak daha sonra yayımlanan öykü ve romanları, çağımızda edebiyat klasikleri arasında yer alsa da, o dönemde fazla ilgi görmedi.Yazar 1849\'da 1.Nikolay\'ın baskıcı rejimine muhalif Petraşevski grubunun üyesi olduğu gerekçesiyle tutuklandı.Kurşuna dizilmek üzereyken cezası sürgün ve zorunlu askerliğe çevrildi.Cezasını tamamlayıp Sibirya\'dan döndükten sonra Petersburg\'da Vremya dergisini çıkarmaya başladı, yazdığı romanlarla tekrar eski ününe kavuştu.Suç ve Ceza Dostoyevski\'nin bütün dünyada en çok okunan başyapıtıdır.', 'img/books/1.png'),
(2, 'Otomatik Portakal', 'Anthony Burgess', 'İş Bankası Kültür Yayınları', 'Roman', 176, 10, 'Tüm hayvanların en zekisi, iyiliğin ne demek olduğunu bilen insanoğluna bir baskı yöntemi uygulayarak onu otomatik işleyen bir makine haline getirenlere kılıç kadar keskin olan kalemimle saldırmaktan başka hiçbir şey yapamıyorum…* Karabasan gibi bir gelecek atmosferi… Geceleyin sokakları terörize eden, yaşamları şiddet üzerine kurulu gençler ve bu hikâyenin anti-kahramanı Alex... Yayımlandığı günden bu yana *kült roman* özelliğini kaybetmeyen Otomatik Portakal’ın 15 yaşındaki kahramanı, *iyi ya da kötü nedir?*, *İnsan özgür iradesiyle kaderini seçebilir mi?* gibi soruların yanıtlarını kurcalarken, şiddet dolu sahnelere Beethoven’ın, Mozart’ın müziği eşlik ediyor; Alex ve *çete kardeşleri* Pete, Georgie ve Aptalof, yarattıkları yepyeni dilin kelimelerini okurun zihnine kazıyorlar. Ünlü yönetmen Stanley Kubrick tarafından 1971’de filme de çekilen Otomatik Portakal tüm zamanların en sarsıcı romanlarından. *Cockney dilinde (İngiliz argosu) bir deyiş vardır. ‘Uqueer as as clockwork orange’. ', 'img/books/2.png'),
(3, 'Beyaz Diş', 'Jack London', 'İş Bankası Kültür Yayınları', 'Roman', 258, 9, 'Jack London’ın Issız Diyarı, yabanı, buz kalpli Kuzey Toprakları’ndaki hayatı konu edindiği ikinci romanı Beyaz Diş’tir. Vahşetin Çağrısı’na kendini bırakmış bir annenin yavrusu Beyaz Diş’in diyarıdır anlatılan. Onun hayranlık uyandırıcı zekası ve içgüdüleriyle kendini var edişinin ve \"insan tanrılar\"ın yaşamına geri dönüşünün enfes hikayesi...', 'img/books/3.png'),
(4, 'Cesur Yeni Dünya ', 'Aldous Huxley', 'İthaki Yayınları', 'Roman', 272, 15, 'İngiliz yazar Aldous Huxley’nin 1932 yılında yayımlanan Cesur Yeni Dünya adlı eseri, distopya edebiyatının dünyadaki en güçlü örnekleri arasında yer alıyor. Hiciv türünde yayımladığı eserler ile döneminin en dikkat çekici yazarlarından olan Huxley, Cesur Yeni Dünya’da eleştirel bakış açısını hayal gücü ve kara mizah ile harmanlıyor. Böylece yazar, eserinde geleceğin modern toplumuna ağır bir insanlık dersi veriyor.\r\n\r\nRomanını Birinci ve İkinci Dünya Savaşları arasındaki dönemde kaleme alan Aldous Huxley, okurlara 30’lu yılların karamsar atmosferini güçlü bir şekilde hissettiriyor. Savaşın ve gelişen teknolojinin insanlık üzerinde yarattığı etkiye dikkat çeken yazar, eserini 1946’da - İkinci Dünya Savaşı’nın bir yıl sonrasında - yeniden gözden geçiriyor. Kitaba bu süreçte eklediği önsöz ise Huxley’nin eleştiri gücünü en çarpıcı şekliyle ortaya koyuyor. ', 'img/books/4.png'),
(5, '1984', 'George Orwell', 'Can Yayınları', 'Roman', 352, 12, 'Parti’nin dünya görüşü, onu hiç anlayamayan insanlara çok daha kolay dayatılıyordu. Her şeyi yutuyorlar ve hiçbir zarar görmüyorlardı çünkü tıpkı bir mısır tanesinin bir kuşun bedeninden sindirilmeden geçip gitmesi gibi, yuttuklarından geriye bir şey kalmıyordu.\r\n\r\nGeorge Orwell’in kült kitabı Bin Dokuz Yüz Seksen Dört, yazarın geleceğe ilişkin bir kâbus senaryosudur. Bireyselliğin yok edildiği, zihnin kontrol altına alındığı, insanların makineleşmiş kitlelere dönüştürüldüğü totaliter bir dünya düzeni, romanda inanılmaz bir hayal gücüyle, en ince ayrıntısına kadar kurgulanmıştır. Geçmişte ve günümüzde dünya sahnesinde tezgâhlanan oyunlar düşünüldüğünde, ütopik olduğu kadar gerçekçi bir romandır Bin Dokuz Yüz Seksen Dört. Güncelliğini hiçbir zaman yitirmeyen bir başyapıttır; yalnızca yarına değil, bugüne de ilişkin bir uyarı çığlığıdır.', 'img/books/5.png'),
(6, 'Hayvan Çiftliği', 'George Orwell', 'Can Yayınları', 'Roman', 152, 7, 'Distopik romanlarıyla ünlenen İngiliz Yazar George Orwell tarafından 1945 yılında yayımlanan Hayvan Çiftliği adlı roman, masalsı atmosferinin altında derin bir sistem eleştirisi barındırıyor. Fabl türünde kaleme alınan eser, yazarın 1984 adlı romanıyla birlikte en geniş kitlelere ulaşan yapıtları arasında yer alıyor. Ön yüzünde bir çiftlik ve içinde yaşayan hayvanları konu edinen roman; devletleri, yönetim biçimlerini ve toplumları sembolik olduğu kadar sade bir anlatımla ele alıyor.  Orwell’in çağdaş klasikler arasında değerlendirilen Hayvan Çiftliği romanı, dünya edebiyatının en dikkat çekici hiciv romanları arasında bulunuyor. Romanının alt metninde birden fazla yönetimin olumsuz yönüne yer veren yazar, ana temasını sosyalizm eleştirisi üzerine kuruyor. Orwell, ideoloji bakımından kendisi de sosyalizme eğilimli olmasının yanı sıra romanında totaliter yönetime meydan okuyor.', 'img/books/6h.png'),
(7, 'Altıncı Koğuş', 'Anton Çehov', 'İş Bankası Kültür Yayınları', 'Roman', 68, 5, 'Çehov bir taşra kasabasındaki akıl hastanesinde geçen bu novellasında, eğitimli bir hasta olan İvan Dmitriç ile Doktor Andrey Yefimıç arasındaki felsefi çatışmaya odaklanır. İvan Dmitriç maruz kaldıkları adaletsizliğe, içinde yaşamaya zorlandıkları berbat koşullara karşı çıkarken, Andrey Yefimıç bunları görmezden gelmekte ısrar eder ve durumu değiştirmek için kılını bile kıpırdatmaz. Doktor sonunda içine düştüğü “felsefi” yanılgının farkına vardığında ise artık iş işten geçmiştir. Altıncı Koğuş, Rusya’nın ve ülkenin sorunlarıyla ilgilenmek yerine onları uzaktan izlemeyi tercih eden elit Rus aydınının “deliliği”nin simgesidir adeta. Altıncı Koğuş, Russkaya Mısl dergisinin 1892 kasım sayısında yayımlandığında büyük ilgi görmüştü. Hatta Lenin’in de yapıtı okuduktan sonra dehşete kapıldığı, “Kendimi Altıncı Koğuş’a kapatılmış gibi hissettim” dediği rivayet edilir. ', 'img/books/7.png'),
(8, 'Bir İdam Mahkumunun Son Günü', 'Victor Hugo', 'İş Bankası Kültür Yayınları', 'Roman', 130, 6, 'Şair: \"Nasıl ilginç olsun ki? Suçlu ve üstelik işlediği suçtan pişmanlık da duymuyor. Mesela ben olsaydım, tersini yapar, şerefli bir aileden gelmiş ve iyi bir eğitim almış bir mahkûmun öyküsünü anlatırdım. Aşk, kıskançlık ve suç... Hatta birden fazla suç. Sonrasında ise pişmanlıklar, pişmanlıklar... Ancak toplumun yasaları serttir. Sonunda ölmeli! İşte bu aşamadan sonra da idam cezası konusunu işlerdim. İşte böyle!..\"', 'img/books/8.png'),
(9, 'Tutunamayanlar', 'Oğuz Atay', 'İletişim Yayınları', 'Türk Edebiyatı', 724, 45, 'Ülkemizin en değerli yazarlarından biri olan Oğuz Atay’ın yazıldığı dönemde büyük tartışma konusu olmuş eseri Tutunamayanlar, 1972 yılında yayımlanmıştır. Eser, bilinç-akışı tekniğiyle döneme damgasını vurarak Türk Edebiyatı’nda yeni bir çağı başlatmıştır. Pek çok eleştirmen, Tutunamayanlar’ı Türk Dili’nde yazılmış en iyi eser olarak değerlendirmektedir.  Tutunamayanlar Oğuz Atay ismiyle özdeşleşmiş bir roman olarak, büyük yazarımızın hayatından izler taşımasıyla da kısmen otobiyografik bir eser olarak da değerlendirilebilir. Roman, son derece üst düzey diliyle çevirisi en zor romanlar arasında yer alır. Tutunamayanlar, sadece birkaç dile çevrilebilmiştir. “Het leven in stukken” adı altında Flemenkçeye (Hollanda Dili) çevrilen eser, eserin Hollandalı çevirmenine ödül kazandırmıştır.  Tutunamayanlar konusu itibariyle intihar eden arkadaşının geçmişini araştıran Turgut Özben’in, söz konusu arkadaşı Selim Işık’ın modern hayata neden “Tutunamadığı”nı öğrenme çabasını anlatmaktadır. Romanda Turgut’un karşılaştığı her kişi Selim Işık’ı tanıyan kişilerdir ve her biri Turgut’a Selim’in farklı yönlerini aktarmaktadır.  İletişim Yayınları’nın en prestijli kitaplarından biri olan Tutunamayanlar, ülkemizde olduğu kadar Dünya çapında da merak konusu olan eserlerden biridir.  Her yıl çok satan kitaplar arasında yer alan Eser, TRT Roman Ödülü’ne sahiptir. Tutunamayanlar romanının ilk baskısı 1000 TL gibi bir fiyat ile alıcı bulmuştur.', 'img/books/9.png'),
(10, 'Fahrenheit 451', 'Ray Bradbury', 'İthaki Yayınları', 'Roman', 208, 15, 'Amerikan edebiyatının öne çıkan yazarlarından Ray Bradbury’nin 1953 yılında yayımlanan eseri Fahrenheit 451, on yıllar öncesinden bugünün ve uzak geleceğin dünyasına sert eleştiriler savuruyor. Distopik bir kurgusal düzlemde ilerleyen eser, teknolojinin gelişmesiyle birlikte toplumun gerileyen sanat ve düşünce dünyasını ele alıyor.  Ray Bradbury’nin karanlık bir geleceği konu aldığı Fahrenheit 451 romanı, bilim kurgu ögelerini baskı rejimi ve robotlaşmış bir toplumla harmanlıyor. Kitabın olay örgüsü, itfaiyecilerin yangın söndürmek yerine kitap yakmakla görevlendirildiği totaliter bir düzen etrafında şekilleniyor. Roman, adını ise kitapların yanma derecesi olan ısı ölçüsünden alıyor.  24’üncü yüzyılda geçen Fahrenheit 451’de toplum yaşamı, skolastik düşüncenin hakim olduğu Orta Çağ’la büyük benzerlik gösteriyor. Bradbury, kitabına yönelik yaptığı açıklamalarda romanı yazmaktaki amacının, televizyonun okumaya olan ilgisini körelttiğini vurgulamak olduğunu dile getiriyor. Yazar, bu noktada eleştirisinin herhangi bir yönetimden ziyade doğrudan halka yönelik olduğunu açıklıyor. Eserinde kitapları yakanlarla okumayanlara aynı suçu yükleyen yazar, topluma zarar veren asıl unsurun düşünmeyi reddetmek olduğunun altını çiziyor.', 'img/books/10.png'),
(11, 'Dönüşüm', 'Franz Kafka', 'İş Bankası Kültür Yayınları', 'Roman', 74, 4, 'Bir sabah, Gregor Samsa kötü rüyalar görüp uyandığında, kendini yatağında korkunç dev bir böceğe dönüşmüş halde buldu. Zırh gibi sertleşmiş olan sırtının üzerinde yatıyordu ve başını biraz kaldırdığında karnının kahverengi, kıvrımlı, katman katman ve sertleşmiş olduğunu gördü. Bu yükseklikte, kayıp düşmeye hazır olan yorganın karnında durması mümkün değildi. Yuvarlak vücudunun geri kalan kısmına göre acınacak seviyede küçük olan çok sayıda bacağı, gözlerinin önünde çaresizce debeleniyordu.', 'img/books/11.png'),
(12, 'Martin Eden', 'Jack London', 'İş Bankası Kültür Yayınları', 'Roman', 520, 15, 'Jack London’ın yarı otobiyografik romanı Martin Eden, 20. yüzyıl başında sosyal ve ideolojik meseleler ağırlıklı içeriğiyle Amerikan edebiyatında büyük ölçüde kabul görmüştür. London farklı sınıflar arasındaki zihniyet ve değer farklarını gözlerimizin önüne sererken, statü ve servetin Amerikan toplumundaki hayati önemine işaret eder. Romanın ana temalarından biri, başarı ve refah yolunun sosyal sınıf farkı gözetilmeksizin herkese açık olduğu şeklinde özetlenebilecek Amerikan Rüyası’dır. Ya da bu idealin yarattığı muazzam hayal kırıklığı…  London, romanı bir sanatçının çıraklıktan olgunluğa geçiş sürecini işleyen Künstlerroman geleneğinde yazmıştır. Martin’in aşkı uğruna eğitimsiz genç bir işçiden başarılı ve rafine bir yazara dönüşüm mücadelesini anlatır. Kahramanı hedefine ulaştığında ise motivasyonunu ve heyecanını çoktan yitirmiş, trajik bir sona doğru sürüklenmektedir artık…', 'img/books/12.png'),
(13, 'Damızlık Kızın Öyküsü', 'Margaret Atwood', 'Doğan Kitap', 'Roman', 384, 32, '“Biz iki bacaklı rahimleriz, hepsi bu.”   Kadın, “bunaltıcı düşlerden uyandığı” bir sabah, hiçliğe dönüşmüş olarak buldu kendini. Artık bir adı yoktu, düşüncesi, benliği, arzusu yoktu ama bir rahmi vardı. Yaşamını kolonilere sürülmeden, öldürülmeden, Damızlık Kız olarak sürdürmesini sağlayan rahmi. Artık âşık olmayacaktı, sevmeyecekti, onaylanmış bir dilin ötesine geçmeyecekti. Duvarlara asılmış sıra sıra cesetler, tek gerçeğin savaş ve üreme olduğunu hatırlatıyordu. Özgürlük hatırlanmayacak kadar uzaktaydı…   Margaret Atwood’un başyapıt niteliğindeki feminist distopyası Damızlık Kızın Öyküsü, bütün distopyalar gibi geleceğe dair bir paranoyayı değil, içinde yaşadığımız gerçeğin ta kendisini dile getiriyor. Erkek egemen muhafazakâr bir rejimin üremeyle sınırlandırdığı, mahrem örtülerin  ardına gizlediği kadın bedenleriyle bize aşina gelen bir gerçeğin.   Anlatılan bizim hikâyemizdir!', 'img/books/13.png'),
(14, 'Yeraltından Notlar', 'Fyodor Mihayloviç Dostoyevski', 'İş Bankası Kültür Yayınları', 'Rus Edebiyatı', 139, 7, 'Dostoyevskinin bir anti-kahraman başyapıtı olan bu eserde, kendisiyle çelişkiler yaşayan, hayata tutunamayan ve ağır çöküntü yaşayan bir karakter ele alınır. Özellikle varoluşunun kökenlerini sorguladığı bölümlerde yazar, hayal ürünü olarak nitelendirdiği bu anti-kahramanla hem kendini hem de zamanının insanlarını sorgulamaktadır. Yeraltından Notlar, belki de Dostoyevskinin hem bir itirafı hem de döneminin boş insanlarına olan nefretini kustuğu bir kitaptır.   ', 'img/books/14.png'),
(15, 'Satranç', 'Stefan Zweig', 'İş Bankası Kültür Yayınları', 'Roman', 77, 4, 'Bir gece yarısı, New York’tan Buenos Aires’e gitmek üzere büyük yolcu gemisi demir alır. Yolcuların arasında birbirinden habersiz iki satranç ustası dolaşmaktadır: yıllardır satranç tahtasından uzakta bir yaşam süren Dr. B. ve dünya şampiyonu Czentovic. Bu iki usta, gemideki yolcularda büyük ilgi uyandırır ve gerilim dolu turnuva başlar. Stefan Zweig’ın derin psikolojik ve edebiyat birikimi, ölümünden hemen önce tamamladığı uzun hikâyesi Satranç’ta bir kez daha okurla bir araya geliyor. İnsan ruhunun gizemli dünyası, saplantılar ve tutkularla örülmüş hikâye, savaş ve şiddet karşıtı yazarın gözünden 2. Dünya Savaşı’nın ardında bıraktığı yıkıma da tanık olmamızı sağlıyor.', 'img/books/15.png'),
(16, 'Şeker Portakalı', 'Jose Mauro De Vasconcelos', 'Can Yayınları', 'Roman', 200, 18, 'Acı dolu bir hayat sürdürmek ve bunu yaşamın olağan seyri gibi kabul etmek, ta ki hayattaki en gerçek ve karşı konulamaz acının ne olduğunu öğrenene kadar… Şeker Portakalı; yoksulluk ve sevgisizlik içinde yaşayan küçük Zeze’nin dünyasını, okuyucusuna yalnızca minik bir çocuğun gözünden değil, evrensel bir hakikat penceresinden sunuyor.   Brezilyalı yazar Jose Mauro de Vasconcelos’un 1968’de yayımlanan Şeker Portakalı adlı eseri, yalın anlatımı ve çarpıcı hikâyesiyle dünya edebiyatının unutulmaz başyapıtları arasında yer alıyor. Yazarının hayatından izler taşıyan eser, bir çocuğun iç dünyasından yola çıkarak tüm insanlığa acıyla yoğrularak olgunlaşmanın ağırlığını duyumsatıyor.   Gerçekçi anlatımı ve duygu ağırlıklı temasıyla Latin Amerika edebiyatını tüm yönleriyle yansıtan Şeker Portakalı; saflığı, şefkati ve acıyı eksiksiz bir empati ile iliklerinize kadar hissetmenizi sağlayacak.', 'img/books/16.png'),
(17, 'Harry Potter ve Felsefe Taşı', 'J.K. Rowling', 'Yapı Kredi Yayınları', 'Fantastik', 276, 18, '“Harry, elleri titreyerek zarfı çevirince mor balmumundan bir mühür gördü; bir arma – koca bir ‘H’ harfinin çevresinde bir aslan, bir kartal, bir porsuk, bir de yılan.” HARRY POTTER sıradan bir çocuk olduğunu sanırken, bir baykuşun getirdiği mektupla yaşamı değişir: Başvurmadığı halde Hogwarts Cadılık ve Büyücülük Okulu’na kabul edilmiştir. Burada birbirinden ilginç dersler alır, iki arkadaşıyla birlikte maceradan maceraya koşar. Yaşayarak öğrendikleri sayesinde küçük yaşta becerikli bir büyücü olup çıkar.', 'img/books/17.png'),
(18, 'Fareler ve İnsanlar', 'John Steinbeck', 'Sel Yayıncılık', 'Amerikan Edebiyatı', 126, 15, 'Fareler ve İnsanlar, birbirine zıt karakterdeki iki mevsimlik tarım işçisinin, zeki George Milton ve onun güçlü kuvvetli ama akli dengesi bozuk yoldaşı Lennie Small’un öyküsünü anlatır. Küçük bir toprak satın alıp insanca bir hayat yaşamanın hayalini kuran bu ikilinin öyküsünde dostluk ve dayanışma duygusu önemli bir yer tutar. Steinbeck insanın insanla ilişkisini anlatmakla kalmaz insanın doğayla ve toplumla kurduğu ilişkileri de konu eder bu destansı romanında. Kitabın ismine ilham veren Robert Burns şiirindeki gibi; “En iyi planları farelerin ve insanların / Sıkça ters gider…\"', 'img/books/18.png'),
(19, 'Anna Karenina', 'Lev Nikolayeviç Tolstoy', 'İş Bankası Kültür Yayınları', 'Rus Edebiyatı', 1062, 22, 'Anna girdiği her ortamda dikkatleri üzerine çeken güzel bir kadındır, üstelik zenginlik içinde geçen hayatında arzu ettiği her şeye sahiptir. Üst düzey bir devlet görevlisi olan nazik eşi Aleksey Aleksandroviç ve oğluyla yaşadığı hayat günbegün ona sıkıcı gelmeye başlar ve kendini derin mutsuzluğun koynunda bulur. Bir gün abisinin ve eşinin aralarını düzeltmek üzere Moskova’ya gittiğinde orada zengin bir subay olan Kont Vronski ile tanışır.  Anna, Rusya’da kapitalizmin ve burjuvazinin altın çağını sürmeye başladığı bir dönemde, yasak aşkını kimseden çekinmeden ve saklanma gereği duymadan yaşamaya başlar. Onun dışlanması ise ahlak kurallarına bağlı kalmaması yüzünden değil, burjuvazinin ikiyüzlülüğüne bağlı kalmaması sebebiyle olur.  Anna Karenina edebiyat tarihinin büyük yazarı Tolstoy’un aşkı, tutkuyu, ihaneti merceğine alarak 19. yüzyıl Rusya’sına odaklandığı en önemli yapıtı…', 'img/books/19.png'),
(20, 'Beyaz Geceler', 'Fyodor Mihayloviç Dostoyevski', 'İş Bankası Kültür Yayınları', 'Rus Edebiyatı', 218, 8, '“Sevmek, güzel birine âşık olmak değil, o kişide bilmediğin bir zamanın, beklenmedik bir anında kendini bulmaktır.”     Genç bir adam, parlak ay ışıklarının aydınlattığı bir St. Petersburg gecesi ve yalnız bir kadın…     Beklenti, fedakârlık, acı, keder ve hayal kırıklığının aşkın içinde kendine nasıl yer bulduğunu anlatan Beyaz Geceler, bu anlamda diğer Dostoyevski eserleri arasında farkını ortaya koyuyor.     Kahramanın, genç ve güzel Nastenka’yla tanışması, ona âşık olması ve onun başka birini bekliyor olduğunu öğrenmesiyle birlikte yaşadıkları kararsızlık, belirsizlik ve bekleyiş içindeki bu üç karakterin yaşadığı dört beyaz gece, aynı zamanda bir film senaryosudur.', 'img/books/20.png'),
(21, 'Veba Geceleri', 'Orhan Pamuk', 'Yapı Kredi Yayınları', 'Türk Edebiyatı', 544, 27, 'Orhan Pamuk’un üzerinde 5 yıldır çalıştığı Veba Geceleri, 1901 yılında 3. Veba Pandemisi döneminde Osmanlı’nın 29. Vilayeti Minger adasında geçiyor. Hem sürükleyici bir siyaset ve aşk romanı hem de Pamuk’un salgın, karantina, devlet ve birey konularını bir masal havasıyla tartıştığı bu tarihi roman, konusuyla yaşadığımız günlere de ışık düşürüyor.\r\n\r\n1901 baharında Osmanlı İmparatorluğu’nun 29. vilayeti Minger Adası’nda veba salgını baş gösterince Sultan Abdülhamit önce Sağlık Başmüfettişi kimyager Bonkowski Paşa’yı, onun arkasından da genç ve başarılı Doktor Nuri’yi salgını durdurması için adaya gönderir. Padişah kısa bir süre önce genç doktoru, sarayda hapis hayatı yaşattığı ağabeyi önceki padişah V. Murat’ın kızı Pakize Sultan ile evlendirmiştir ve Pakize Sultan da bu yolculukta kocasına eşlik etmektedir. Adada ise genç ve milliyetçi Osmanlı subayı Kolağası Kâmil, onun âşık olduğu adalı Zeynep ve her şeye yetişmeye çalışan Vali Sami Paşa ile güzel sevgilisi Marika vardır. Karantina yasaklarına itaat edilmesi için çaba harcayan bu insanların vebayla, adadaki geleneklerle ve sonunda birbirleriyle ve ölüm tehditleriyle savaşının ve yaşadıkları aşkların hikâyesidir Veba Geceleri.', 'img/books/21.png'),
(22, 'Yıldız Tozu - Resimli Edisyon', 'Neil Gaiman', 'İthaki Yayınları', 'Roman', 256, 33, 'Viktoryen çağın şafağında, mahmur İngiliz kırsalında Duvar Köyü uzanır; ismiyle müsemma bu köyün etrafını verimli çimenler üzerinde yükselen taş duvarlar çevreler. Duvar’daki sükûnet dolu yaşantı her dokuz yılda bir, yalnızca bir kereliğine bozulur ve fanilerle periler benzersiz bir panayır için bir araya gelir.\r\n\r\nDuvar’daki bu panayırda genç Tristran Thorn kalbini köyün güzeline kaptırıverir; ama bu güzel, hem Tristran’ın hem de kendisinin serin bir ekim ayı akşamında kayarken gördükleri yıldız kadar soğuk ve mesafelidir. Sevgisine karşılık bulmak için Tristran hiç düşünmeden o kayan yıldızı yakalayacağına yemin eder ve onu kadim duvarın ötesindeki, aklının hayalinin almayacağı bir dünyaya götürecek yolculuğuna başlar.', 'img/books/22.png'),
(23, 'Başka', 'Ege Soley', 'Doğan Novus', 'Kişisel Gelişim', 224, 25, 'Bazı şeyler var hayatta, insan yapana kadar yapabileceğini bilmiyor. Daha fenası, inanmıyor da elinden gelebileceklere. Çizeceği resimlere, söyleyebileceği şarkılara, anlatacağı hikâyelere inanası gelmiyor. Kendini bitmiş, elindekiler çoktan tükenmiş gibi hissediyor. Oysa hepimizin içinde, coşkuyla açabilmek için doğru topraklara ekilmeyi bekleyen tohumlar uyuyor.\r\n\r\nSakin ve Yakın kitaplarının yazarı Ege Soley’le bu kez “bambaşka” bir yolculuğa çıkıyoruz. İngiltere’de siyaset eğitiminin ardından her şeye sıfırdan başlama kararıyla, kendini Paris’te bir çiçekçide çırak olarak çalışırken bulan Ege’nin deneyimleri, bize bu mesleğin hiç tahmin edilemeyecek kapılarını aralarken hayata her an yeniden başlamanın da mümkün olduğunu hatırlatıyor...', 'img/books/23.png'),
(24, 'Mutluluğa Övgü', 'Matthieu Ricard', 'Doğan Novus', 'Roman', 344, 34, 'Kim mutlu olmayı istemez? Ama onu nasıl bulacağımızı, nasıl koruyacağımızı ve hatta nasıl tasvir edeceğimizi bilemeyiz.\r\n\r\nMutluluk çaba gerektiren, insanı rahatlatan ve herkes tarafından erişilebilen bir şey olarak tanımlanabilir mi? Mutluluğu dışarıda aramak yerine, kendi içimizde mi aramalıyız? Mutluluk kısa süren zevklerle yakalanabilir mi? Yoksa mutluluk, kişisel olmaktan çok şefkat uyandıran, diğer insanların iyiliğini isteyen bir duygu mudur? Gerçekten mutluysak dünyayı değiştirebilir miyiz? İnsanlara duyduğumuz şefkat, nefreti sona erdirme ve sevmediğimiz insanları bile mutlu etme düşüncesine dönüşebilir mi?\r\n\r\n\"Dünyanın en mutlu insanı\" olduğu sinirbilim ölçümlemeleriyle de kanıtlanmış olan Fransız Budist keşiş Matthieu Ricard, bu kitapta kendi mutsuzluğundan yola çıkarak bulduğu mutluluk formülünü paylaşıyor bizimle. Fransa\'nın en önemli üniversitelerinden birinde moleküler biyoloji alanında yıldızı parlak bir bilim insanı iken bir anda her şeyi bırakıp tası tarağı toplayarak Hindistan ve Tibet\'e doğru uzun bir yolculuğa çıkıyor Ricard. Onun mutsuzluğuna çare arayışının bir sonucu olan bu kitap ise, bizim için mutluluğa ulaşmanın yol haritası oluyor. Ve işe mutluluğun ne olduğunu anlayarak başlıyoruz…\r\n\r\n', 'img/books/24.png'),
(25, 'Yağmur Kaçağı', 'Attila İlhan', 'İş Bankası Kültür Yayınları', 'Roman', 88, 12, 'Ne Vakit Maçka\'dan Geçsem\r\nLimanda Hep Gemiler Olurdu\r\nAğaçlar Kuşlar Gibi Gülerdi\r\nBir Rüzgâr Aklımı Alırdı\r\nSessizce Bir Cıgara Yakardın\r\nParmaklarımın Ucunu Yakardın\r\nKirpiklerini Eğerdin Bakardın\r\nÜşürdüm İçim Ürperirdi\r\nFelâketim Olurdu Ağlardım\r\nÜçüncü Şahsın Şiiri \'Nden', 'img/books/25.png'),
(26, 'Balıkçı ve Oğlu', 'Zülfü Livaneli', 'İnkılap Kitabevi', 'Roman', 140, 20, 'Toplumsal konulara duyarlılığı ile tanınan edebiyatçı ve fikir adamı Zülfü Livaneli, bu kez Ege balıkçılarının ve hayal kurmaktan bile mahrum bırakılan göçmenlerin kaderine eğiliyor. Usta edebiyatçı Livaneli, Balıkçı ve Oğlu ile son yılların en can yakıcı ve büyük dramı “göçmenliği” balıkçı Mustafa, Mesude ve Samir bebek üzerinden anlatıyor. O güne dek sıcak evlerinde televizyondan izledikleri haberlerden aşina oldukları ölü insan bedenleri ve yarı ölü bir bebek evliliklerinin tam ortasına düşerek bir bomba etkisi yaratıyor; aile ilişkilerini bambaşka bir çehreye büründürüyor. Balıkçı ve Oğlu, Ege’nin tarihinden bugününe, balık çiftliklerine ve rant hırsıyla dağlara, kıyılara saldıran şirketlerin yarattığı ekolojik yıkıma dair çok şey söylüyor. Bunun ötesinde göçmenlerin bir bilinmeze doğru göze aldıkları yolculuğu, hayatta kalma çabalarını ya da ölümü; kısacası “deryaya yakın, dünyadan uzak” yaşamlarını odağına alıyor. Livaneli’nin belki de en şiirsel romanı olan Balıkçı ve Oğlu; aile, aşk, ebeveynlik, evlat, kadın dayanışması, dostluk, göç, doğa üzerine çağdaş bir epope. Zülfü Livaneli’nin, uzun bir aradan sonra yazdığı ve heyecanla beklenen yeni romanı Balıkçı ve Oğlu, ustalıkla seçilen tasvirlerle okurun zihninde capcanlı bir anlatı oluşturuyor. ', 'img/books/26.png'),
(27, 'Empedokles\'in Dostları', 'Amin Maalouf', 'Yapı Kredi Yayınları', 'Roman', 216, 18, 'Romanlarıyla olduğu kadar deneme kitaplarıyla da ilgi çeken Maalouf, Empedokles’in Dostları’nda bu kez geleceğe yönelik bir kurguyla dönüş yapıyor. Ölümcül Kimlikler ve Uygarlıkların Batışı kitaplarında yer verdiği eleştirel gözlemlerin izinde yarı distopik bir dünya çiziyor. Platon’un mağarasından çıkıp Empedokles’in Dostları’yla tanışmaya davet ediyor bizi.\r\n \r\nAtlas Okyanusu kıyısındaki küçük Antioche adasının yalnızca iki sakini vardır: Orta yaşın verdiği olgunlukla sessiz bir hayat sürmek isteyen Alec ile yazdığı ilk romanının yakaladığı başarı sonrası her şeyi ardında bırakan esrarengiz Ève. Birbirlerinden uzakta, kırılgan yalnızlıklarının tadını çıkaran bu iki insanın yolu bir gün elektriğin, telefonların, televizyon yayınlarının, internetin, kısacası her türlü iletişim aracının etkisiz hale gelmesiyle kesişir.\r\nGerçeğe ulaşma imkânı kalmayınca fısıltı gazetesi işlemeye başlar: Gezegen bir nükleer felaketin eşiğindedir, Amerika küresel ölçekte bir terör saldırısına maruz kalmıştır, insanlığın hayatını kolaylaştıran teknolojik gelişmeler artık insanlığın sonunu getirmiştir...\r\nTüm dünya bu söylentilerle çalkalanırken, kendilerine Empedokles’in Dostları diyen, son derece gelişmiş bir teknolojiye ve tıp bilgisine sahip bir grup gizemli insan bu karmaşaya son vermek üzere çıkagelir. Alec bu insanların kim olduğunu öğrenmeye çalışırken, içinde yaşadığımız dünyanın çelişkileriyle de yüzleşmek zorunda kalır. Hiçbir şey artık eskisi gibi olmayacaktır.\r\n \r\n“Hayal kırıklığı içeren bu satırları yazarken hikâyenin sonuna geldiğim izlenimindeyim. Geldiler, üstünlük kurdular, dünyada hem kaygı hem de umut rüzgârları estirdiler, sonra da gittiler.”', 'img/books/27.png'),
(28, 'Kan Varsa', 'Stephen King', 'Altın Kitaplar', 'Roman', 432, 36, 'Kan varsa haber de vardır...\r\nHabercilerin kullandığı bir deyişti bu ve o gün bir bombanın patlatıldığı Albert Macready Ortaokulu’nda kesinlikle kan vardı. Finders Keepers Dedektiflik Ajansı\'nda günlük işleriyle ilgilenen Holly Gibney\'nin dikkatini çeken ise bambaşka bir ayrıntıydı. O, kanın kokusunu alıp ilk haberi yapan muhabire takılmıştı. Holly\'nin adama odaklanmasının geçerli bir nedeni vardı, çünkü o bir Yabancı\'ydı.\r\nKan Varsa her biri okuru kendi korku dolu dünyasına çeken dört uzun öyküden oluşuyor. Holly’nin ilk yalnız macerasının dışında Bay Harrigan’ın Telefonu, Chuck’ın Hayatı ve Sıçan öyküleri uykularınızı kaçıracak.', 'img/books/28.png'),
(29, 'Balinanın Karnında', 'George Orwell', 'İthaki Yayınları', 'Roman', 160, 12, 'George Orwell üzerine çalışmalarıyla da bilinen Peter Davison’a göre yazarın denemelerini bu kadar başarılı yapan nitelikler, onun alt sınıflara ilgisi, bağımsız sosyalizm yorumu, edebi ve sosyal eleştirmenliği, emperyalizm karşıtlığı ve popüler kültüre olan alakasıydı. Orwell’in Balinanın Karnında’daki denemelerini okuyunca bu yorumun ne kadar doğru olduğunu bir kere daha anlıyoruz.\r\n\r\nOrwell’in bu kitapta derlenen denemelerinde yazarın sanat ve propagandaya dair fikirlerini, İspanya İç Savaşı’ndaki deneyimlerini ve İngiltere’deki antisemitizmi öğreniyor, aynı zamanda Henry Miller, Shakespeare ve Tolstoy gibi yazarlara dair yorumlarını da okuyoruz. Balinanın Karnında, ilgileri geniş bir yelpazeye yayılan bir yazarla ufuk açıcı bir yolculuk.', 'img/books/29.png'),
(30, 'Vezir Gambiti', 'Walter Tevis', 'İthaki Yayınları', 'Roman', 336, 25, 'Vezir Gambiti, feminizme, satranca, bağımlıklara dair hem bir yetişkinliğe adım romanı hem bir gerilim hikâyesi hem de bir spor macerası. Farklı türlere dokunan ve birçok konuya dair söyleyecek sözleri olan bu roman, bilimkurguyu da suç hikâyeleri kadar rahatlıkla yazabilen, çok yönlü bir akla sahip Walter Tevis’in kaleminden çıkabilirdi sadece.\r\n\r\nSekiz yaşında ve hayatta yapayalnız kalmış Beth Harmon diğerleri arasında göze batmayan, sıradan bir çocuktu, ta ki ilk gördüğü andan itibaren aklını çelen bu garip oyunla tanışana kadar. Bu altmış dört karelik tahta üzerinde bambaşka bir gelecekle karşılaşan Beth adım adım, her hamlesinde didinip çabalayarak kadınlara kapalı satranç camiasının zirvesini hedeflemekte. Her oyunda rakibinin yanı sıra koca bir geleneğe karşı da hamle yapıyor. Durumu tartıyor, geleceği öngörüyor, rakibinin aklını okumaya çalışıyor ve taşları yerinden oynatıyor. Satrancın siyah beyaz dünyasında zirve dâhilere her zaman açık olsa da gerçekte işler bundan biraz farklı işliyor.\r\n\r\nWalter Tevis, Vezir Gambiti’nde zekâ dolu ve usta işi bir oyunu tek bir cinsiyete sıkıştırmaya çalışanları ezip geçerken dâhi bir kadının en az yaptığı hamleler kadar girift iç dünyasını sıkı bir serüvenle anlatıyor.', 'img/books/30.png');

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `users`
--

CREATE TABLE `users` (
  `usersId` int(10) UNSIGNED NOT NULL,
  `usersName` char(90) NOT NULL,
  `usersEmail` varchar(90) NOT NULL,
  `usersPassword` varchar(30) NOT NULL,
  `usersAddtime` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Tablo döküm verisi `users`
--

INSERT INTO `users` (`usersId`, `usersName`, `usersEmail`, `usersPassword`, `usersAddtime`) VALUES
(4, 'Elif Bengü Kızılay', 'bengukizilay@gmail.com', '1', '2021-05-20 02:16:38'),
(5, 'burak seyit kara', 'burak@burak.com', '123456789', '2021-05-20 02:17:02'),
(6, 'Muhammed Emre Kuş', 'muhammedemrekus@gmail.com', '1qaz2wsx1221', '2021-05-22 12:02:52'),
(7, 'burak kara', 'burak1@burak.com', '123456789', '2021-06-07 14:37:22'),
(8, 'asdsadsadad', 'asdasdas@sadada.com', '123123123', '2021-06-13 16:21:12'),
(9, 'BUURAKAKSDA', 'asdlasdklas@dasda.com', '$2y$10$5zUozQ2Q827dsylI.Z7SaO7', '2021-06-13 16:26:40'),
(10, 'burakkkkkk', 'burakkarakara@kara.com', '$2y$10$P1E7JmBBYpxQF.62dazGNOg', '2021-06-13 16:34:05');

--
-- Dökümü yapılmış tablolar için indeksler
--

--
-- Tablo için indeksler `books`
--
ALTER TABLE `books`
  ADD PRIMARY KEY (`bookId`);

--
-- Tablo için indeksler `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`usersId`),
  ADD UNIQUE KEY `usersName` (`usersName`),
  ADD UNIQUE KEY `usersEmail` (`usersEmail`);

--
-- Dökümü yapılmış tablolar için AUTO_INCREMENT değeri
--

--
-- Tablo için AUTO_INCREMENT değeri `books`
--
ALTER TABLE `books`
  MODIFY `bookId` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=31;

--
-- Tablo için AUTO_INCREMENT değeri `users`
--
ALTER TABLE `users`
  MODIFY `usersId` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
